// Copyright (c) Six Labors.
// Licensed under the Six Labors Split License.

using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using SixLabors.Fonts.Tests.Unicode;
using SixLabors.Fonts.Unicode;

namespace UnicodeTrieGenerator;

/// <content>
/// Contains the generator for the ASCII bidi classification tables.
/// </content>
public static partial class Generator
{
    private const string UnicodeOutputRelativePath = @"src\SixLabors.Fonts\Unicode";

    /// <summary>
    /// The number of values the ASCII tables cover.
    /// </summary>
    private const int AsciiTableLength = 128;

    /// <summary>
    /// Generates the compile-time constant ASCII bidi tables consumed by the
    /// bidirectional analysis fast path. Every byte derives from the Unicode
    /// source data: the character types from the UnicodeData bidi category field,
    /// the bracket types and pairings from BidiBrackets, and the pairing keys from
    /// the canonical mapping the same rows define. A unit test asserts the
    /// generated data matches the general classification path at runtime.
    /// </summary>
    public static void GenerateAsciiBidiTables()
    {
        byte[] characterTypes = new byte[AsciiTableLength];
        byte[] pairedBracketTypes = new byte[AsciiTableLength];
        byte[] pairedBracketValues = new byte[AsciiTableLength];

        using (StreamReader sr = GetStreamReader("UnicodeData.txt"))
        {
            string? line;
            while ((line = sr.ReadLine()) != null)
            {
                string[] parts = line.Split(';');
                if (parts.Length > 4)
                {
                    int codePoint = ParseHexInt(parts[0]);
                    if (codePoint < AsciiTableLength)
                    {
                        _ = UnicodeTypeMaps.BidiCharacterTypeMap.TryGetValue(parts[4], out BidiCharacterType cls);
                        characterTypes[codePoint] = (byte)cls;
                    }
                }
            }
        }

        Regex regex = BidiBracketRowRegex();
        using (StreamReader sr = GetStreamReader("BidiBrackets.txt"))
        {
            string? line;
            while ((line = sr.ReadLine()) != null)
            {
                Match match = regex.Match(line);
                if (match.Success)
                {
                    int point = ParseHexInt(match.Groups[1].Value);
                    int otherPoint = ParseHexInt(match.Groups[2].Value);
                    if (point < AsciiTableLength)
                    {
                        _ = BidiPairedBracketTypeMap.TryGetValue(match.Groups[3].Value, out BidiPairedBracketType kind);
                        pairedBracketTypes[point] = (byte)kind;

                        // The pairing key is the canonical form of the closing
                        // bracket: the paired point for an opening bracket and the
                        // point itself for a closing one. No ASCII value carries a
                        // canonical decomposition in UnicodeData, so the canonical
                        // form is the value itself.
                        int pairingKey = kind == BidiPairedBracketType.Open ? otherPoint : point;
                        pairedBracketValues[point] = checked((byte)pairingKey);
                    }
                }
            }
        }

        StringBuilder sb = new();
        sb.AppendLine("// Copyright (c) Six Labors.");
        sb.AppendLine("// Licensed under the Six Labors Split License.");
        sb.AppendLine();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("namespace SixLabors.Fonts.Unicode;");
        sb.AppendLine();
        sb.AppendLine("/// <content>");
        sb.AppendLine("/// Contains the generated ASCII bidi classification tables.");
        sb.AppendLine("/// </content>");
        sb.AppendLine("internal partial class BidiData");
        sb.AppendLine("{");

        const string characterTypesDoc = """
            /// <summary>
            /// Gets the bidi character type for every ASCII value as compile-time constant
            /// data the runtime reads directly from metadata. ASCII contains no embedding,
            /// override, or isolate initiators, so the fast path never needs the flag
            /// bookkeeping the general path performs. Generated from the UnicodeData bidi
            /// category field; a test asserts the general classification path agrees.
            /// </summary>
            """;

        const string pairedBracketTypesDoc = """
            /// <summary>
            /// Gets the paired bracket type for every ASCII value as compile-time constant
            /// data; the ASCII brackets are the parentheses, square brackets, and curly
            /// braces. Generated from BidiBrackets; a test asserts the general
            /// classification path agrees.
            /// </summary>
            """;

        const string pairedBracketValuesDoc = """
            /// <summary>
            /// Gets the paired bracket value for every ASCII value as compile-time constant
            /// data: the canonical pairing key the bracket-pair stage matches opening and
            /// closing brackets by, zero for non-brackets. Generated from BidiBrackets; a
            /// test asserts the general classification path agrees.
            /// </summary>
            """;

        AppendTable(sb, "AsciiCharacterTypes", characterTypes, characterTypesDoc);
        sb.AppendLine();
        AppendTable(sb, "AsciiPairedBracketTypes", pairedBracketTypes, pairedBracketTypesDoc);
        sb.AppendLine();
        AppendTable(sb, "AsciiPairedBracketValues", pairedBracketValues, pairedBracketValuesDoc);

        sb.AppendLine("}");

        string path = GetFullPath(Path.Combine(UnicodeOutputRelativePath, "BidiData.AsciiTables.Generated.cs"));
        File.WriteAllText(path, sb.ToString());
    }

    /// <summary>
    /// Appends one constant-data span property: the supplied documentation block
    /// followed by the byte values in rows of sixteen.
    /// </summary>
    /// <param name="sb">The builder receiving the generated source.</param>
    /// <param name="name">The property name.</param>
    /// <param name="values">The table values.</param>
    /// <param name="documentation">The XML documentation block for the property.</param>
    private static void AppendTable(StringBuilder sb, string name, byte[] values, string documentation)
    {
        foreach (string docLine in documentation.Split('\n'))
        {
            sb.Append("    ").AppendLine(docLine.TrimEnd('\r'));
        }

        sb.AppendLine(CultureInfo.InvariantCulture, $"    public static ReadOnlySpan<byte> {name} =>");
        sb.AppendLine("    [");
        for (int row = 0; row < values.Length; row += 16)
        {
            sb.Append("        ");
            for (int col = 0; col < 16; col++)
            {
                int index = row + col;
                sb.Append(CultureInfo.InvariantCulture, $"0x{values[index]:X2}");
                if (index != values.Length - 1)
                {
                    sb.Append(col == 15 ? "," : ", ");
                }
            }

            sb.AppendLine();
        }

        sb.AppendLine("    ];");
    }
}
