// Copyright (c) Six Labors.
// Licensed under the Six Labors Split License.

using System.Globalization;

namespace UnicodeTrieGenerator;

/// <content>
/// Contains code to generate legacy Arabic character mappings.
/// </content>
public static partial class Generator
{
    /// <summary>
    /// The number of bytes in one generated mapping entry.
    /// </summary>
    private const int ArabicLegacyMappingEntrySize = sizeof(ushort) * 2;

    /// <summary>
    /// The mask selecting the low byte of a two-byte character code.
    /// </summary>
    private const ushort LowByteMask = byte.MaxValue;

    /// <summary>
    /// The shift selecting the high byte of a two-byte character code.
    /// </summary>
    private const int HighByteShift = 8;

    /// <summary>
    /// Generates the legacy Simplified and Traditional Arabic character mappings.
    /// </summary>
    /// <remarks>
    /// The mappings are defined by
    /// <see href="https://learn.microsoft.com/en-us/typography/legacy/legacy_arabic_fonts">Microsoft's legacy Arabic font documentation</see>.
    /// The generator reads its machine-readable copies from <c>tests/harfbuzz/src/ArabicPUASimplified.txt</c>
    /// and <c>tests/harfbuzz/src/ArabicPUATraditional.txt</c>. They are not derivable from the Unicode Character Database.
    /// </remarks>
    private static void GenerateArabicLegacyEncodingData()
    {
        List<(ushort CodePoint, ushort MappedCodePoint, string Name)> simplified = ReadArabicLegacyMappings("ArabicPUASimplified.txt");
        List<(ushort CodePoint, ushort MappedCodePoint, string Name)> traditional = ReadArabicLegacyMappings("ArabicPUATraditional.txt");

        using FileStream fileStream = GetStreamWriter("ArabicLegacyEncodingData.Generated.cs");
        using StreamWriter writer = new(fileStream);

        writer.WriteLine("// Copyright (c) Six Labors.");
        writer.WriteLine("// Licensed under the Six Labors Split License.");
        writer.WriteLine();
        writer.WriteLine("// <auto-generated />");
        writer.WriteLine("using System;");
        writer.WriteLine("using System.Buffers.Binary;");
        writer.WriteLine();
        writer.WriteLine("namespace SixLabors.Fonts.Unicode.Resources");
        writer.WriteLine("{");
        writer.WriteLine("    /// <summary>");
        writer.WriteLine("    /// Maps Unicode characters to the private-use codes of legacy Arabic fonts.");
        writer.WriteLine("    /// </summary>");
        writer.WriteLine("    internal static class ArabicLegacyEncodingData");
        writer.WriteLine("    {");
        writer.WriteLine("        /// <summary>");
        writer.WriteLine("        /// The OS/2 version 0 font-page marker for Simplified Arabic.");
        writer.WriteLine("        /// </summary>");
        writer.WriteLine("        public const ushort SimplifiedArabicFontPage = 0xB200;");
        writer.WriteLine();
        writer.WriteLine("        /// <summary>");
        writer.WriteLine("        /// The OS/2 version 0 font-page marker for Traditional Arabic.");
        writer.WriteLine("        /// </summary>");
        writer.WriteLine("        public const ushort TraditionalArabicFontPage = 0xB300;");
        writer.WriteLine();
        writer.WriteLine("        /// <summary>");
        writer.WriteLine("        /// The number of bytes in one source and mapped-code pair.");
        writer.WriteLine("        /// </summary>");
        writer.WriteLine($"        public const int MappingEntrySize = {ArabicLegacyMappingEntrySize};");
        writer.WriteLine();
        writer.WriteLine("        /// <summary>");
        writer.WriteLine("        /// The byte offset of the mapped code within an entry.");
        writer.WriteLine("        /// </summary>");
        writer.WriteLine("        public const int MappedCodePointOffset = sizeof(ushort);");
        writer.WriteLine();
        writer.WriteLine("        /// <summary>");
        writer.WriteLine("        /// Maps a Unicode character to the private-use code used by the selected legacy font page.");
        writer.WriteLine("        /// </summary>");
        writer.WriteLine("        /// <param name=\"fontPage\">The legacy font-page marker.</param>");
        writer.WriteLine("        /// <param name=\"codePoint\">The Unicode character to map.</param>");
        writer.WriteLine("        /// <returns>The private-use code, or zero when the character has no mapping.</returns>");
        writer.WriteLine("        public static ushort GetMappedCodePoint(ushort fontPage, int codePoint)");
        writer.WriteLine("        {");
        writer.WriteLine("            ReadOnlySpan<byte> mappings = GetMappings(fontPage);");
        writer.WriteLine("            int low = 0;");
        writer.WriteLine("            int high = (mappings.Length / MappingEntrySize) - 1;");
        writer.WriteLine("            while (low <= high)");
        writer.WriteLine("            {");
        writer.WriteLine("                int middle = low + ((high - low) >> 1);");
        writer.WriteLine("                int offset = middle * MappingEntrySize;");
        writer.WriteLine("                ushort candidate = BinaryPrimitives.ReadUInt16LittleEndian(mappings.Slice(offset, sizeof(ushort)));");
        writer.WriteLine("                if (codePoint < candidate)");
        writer.WriteLine("                {");
        writer.WriteLine("                    high = middle - 1;");
        writer.WriteLine("                }");
        writer.WriteLine("                else if (codePoint > candidate)");
        writer.WriteLine("                {");
        writer.WriteLine("                    low = middle + 1;");
        writer.WriteLine("                }");
        writer.WriteLine("                else");
        writer.WriteLine("                {");
        writer.WriteLine("                    return BinaryPrimitives.ReadUInt16LittleEndian(mappings.Slice(offset + MappedCodePointOffset, sizeof(ushort)));");
        writer.WriteLine("                }");
        writer.WriteLine("            }");
        writer.WriteLine();
        writer.WriteLine("            return 0;");
        writer.WriteLine("        }");
        writer.WriteLine();
        writer.WriteLine("        /// <summary>");
        writer.WriteLine("        /// Gets the packed mappings for the selected legacy font page.");
        writer.WriteLine("        /// </summary>");
        writer.WriteLine("        /// <param name=\"fontPage\">The legacy font-page marker.</param>");
        writer.WriteLine("        /// <returns>The packed mappings, or an empty span for another font page.</returns>");
        writer.WriteLine("        public static ReadOnlySpan<byte> GetMappings(ushort fontPage)");
        writer.WriteLine("            => fontPage switch");
        writer.WriteLine("            {");
        writer.WriteLine("                SimplifiedArabicFontPage => SimplifiedMappings,");
        writer.WriteLine("                TraditionalArabicFontPage => TraditionalMappings,");
        writer.WriteLine("                _ => []");
        writer.WriteLine("            };");
        writer.WriteLine();

        WriteArabicLegacyMappings(writer, "SimplifiedMappings", simplified);
        writer.WriteLine();
        WriteArabicLegacyMappings(writer, "TraditionalMappings", traditional);

        writer.WriteLine("    }");
        writer.WriteLine("}");
    }

    /// <summary>
    /// Reads one legacy mapping file, keeping the final entry for a repeated Unicode character.
    /// </summary>
    /// <param name="fileName">The source file name.</param>
    /// <returns>The mappings ordered by Unicode character.</returns>
    private static List<(ushort CodePoint, ushort MappedCodePoint, string Name)> ReadArabicLegacyMappings(string fileName)
    {
        Dictionary<ushort, (ushort MappedCodePoint, string Name)> mappings = [];
        foreach (string line in File.ReadLines(GetReferenceSourcePath(fileName)))
        {
            if (line.Length == 0 || line[0] == '#')
            {
                continue;
            }

            string[] fields = line.Split('\t');
            ushort mappedCodePoint = ushort.Parse(fields[0].AsSpan(2), NumberStyles.HexNumber, CultureInfo.InvariantCulture);
            ushort codePoint = ushort.Parse(fields[1].AsSpan(2), NumberStyles.HexNumber, CultureInfo.InvariantCulture);
            string name = fields[2].AsSpan(1).Trim().ToString();
            mappings[codePoint] = (mappedCodePoint, name);
        }

        return mappings
            .OrderBy(static pair => pair.Key)
            .Select(static pair => (pair.Key, pair.Value.MappedCodePoint, pair.Value.Name))
            .ToList();
    }

    /// <summary>
    /// Writes one mapping set as a packed little-endian byte span.
    /// </summary>
    /// <param name="writer">The output writer.</param>
    /// <param name="propertyName">The generated property name.</param>
    /// <param name="mappings">The mappings to write.</param>
    private static void WriteArabicLegacyMappings(StreamWriter writer, string propertyName, List<(ushort CodePoint, ushort MappedCodePoint, string Name)> mappings)
    {
        string label = propertyName[..(propertyName.Length - "Mappings".Length)].ToLowerInvariant();

        writer.WriteLine("        /// <summary>");
        writer.WriteLine($"        /// The {label} Arabic mappings.");
        writer.WriteLine("        /// </summary>");
        writer.WriteLine($"        private static ReadOnlySpan<byte> {propertyName} =>");
        writer.WriteLine("        [");

        foreach ((ushort codePoint, ushort mappedCodePoint, string name) in mappings)
        {
            writer.WriteLine(
                $"            0x{codePoint & LowByteMask:X2}, 0x{codePoint >> HighByteShift:X2}, 0x{mappedCodePoint & LowByteMask:X2}, 0x{mappedCodePoint >> HighByteShift:X2}, // U+{codePoint:X4} {name}");
        }

        writer.WriteLine("        ];");
    }
}
