// Copyright (c) Six Labors.
// Licensed under the Six Labors Split License.

using System.Globalization;
using System.Text.RegularExpressions;

namespace UnicodeTrieGenerator;

/// <content>
/// Contains code to generate Arabic presentation-form fallback data.
/// </content>
public static partial class Generator
{
    /// <summary>
    /// The number of presentation-form columns in each shaping row.
    /// </summary>
    private const int ArabicPresentationFormCount = 4;

    /// <summary>
    /// Matches one row of the Arabic presentation-form table.
    /// </summary>
    [GeneratedRegex(@"\{\s*0x(?<initial>[0-9A-F]+)u,\s*0x(?<medial>[0-9A-F]+)u,\s*0x(?<final>[0-9A-F]+)u,\s*0x(?<isolated>[0-9A-F]+)u\s*\},\s*/\*\s*U\+(?<codePoint>[0-9A-F]+)\s*(?<name>.*?)\s*\*/")]
    private static partial Regex ArabicPresentationFormRegex();

    /// <summary>
    /// Matches one first-character set in an Arabic ligature table.
    /// </summary>
    [GeneratedRegex(@"\{\s*0x(?<first>[0-9A-F]+)u,\s*\{(?<body>.*?)\}\s*\},", RegexOptions.Singleline)]
    private static partial Regex ArabicLigatureSetRegex();

    /// <summary>
    /// Matches one ligature and its component characters.
    /// </summary>
    [GeneratedRegex(@"\{\s*\{(?<components>(?:\s*0x[0-9A-F]+u\s*,?)+)\},\s*0x(?<ligature>[0-9A-F]+)u\s*\}\s*,?\s*/\*\s*(?<name>.*?)\s*\*/")]
    private static partial Regex ArabicLigatureRegex();

    /// <summary>
    /// Matches one hexadecimal character code in a ligature component list.
    /// </summary>
    [GeneratedRegex(@"0x(?<value>[0-9A-F]+)u")]
    private static partial Regex ArabicLigatureComponentRegex();

    /// <summary>
    /// Generates Arabic presentation-form and required-ligature fallback data.
    /// </summary>
    /// <remarks>
    /// The presentation forms and ligatures come from the compatibility decompositions in
    /// <c>UnicodeData.txt</c>. The three private-use compatibility additions are not part of
    /// the Unicode Character Database.
    /// </remarks>
    private static void GenerateArabicFallbackData()
    {
        string source = File.ReadAllText(GetReferenceSourcePath("hb-ot-shaper-arabic-table.hh"));
        List<(ushort CodePoint, ushort Initial, ushort Medial, ushort Final, ushort Isolated, string Name)> forms = ReadArabicPresentationForms(source);
        List<(ushort First, ushort Second, ushort Third, ushort Ligature, string Name)> threeCharacterLigatures = ReadArabicLigatures(source, "ligature_3_table", 2);
        List<(ushort First, ushort Second, ushort Third, ushort Ligature, string Name)> twoCharacterLigatures = ReadArabicLigatures(source, "ligature_table", 1);
        List<(ushort First, ushort Second, ushort Third, ushort Ligature, string Name)> markLigatures = ReadArabicLigatures(source, "ligature_mark_table", 1);

        using FileStream fileStream = GetStreamWriter("ArabicFallbackData.Generated.cs");
        using StreamWriter writer = new(fileStream);

        writer.WriteLine("// Copyright (c) Six Labors.");
        writer.WriteLine("// Licensed under the Six Labors Split License.");
        writer.WriteLine();
        writer.WriteLine("// <auto-generated />");
        writer.WriteLine("using System;");
        writer.WriteLine("using System.Buffers.Binary;");
        writer.WriteLine();
        writer.WriteLine("namespace SixLabors.Fonts.Unicode.Resources");
        writer.WriteLine("{");
        writer.WriteLine("    /// <summary>");
        writer.WriteLine("    /// Provides Arabic presentation forms and required ligatures for fonts without substitution features.");
        writer.WriteLine("    /// </summary>");
        writer.WriteLine("    internal static class ArabicFallbackData");
        writer.WriteLine("    {");
        writer.WriteLine("        /// <summary>");
        writer.WriteLine("        /// The number of presentation forms stored for each character.");
        writer.WriteLine("        /// </summary>");
        writer.WriteLine($"        public const int PresentationFormCount = {ArabicPresentationFormCount};");
        writer.WriteLine();
        writer.WriteLine("        /// <summary>");
        writer.WriteLine("        /// The number of bytes in one character and its presentation forms.");
        writer.WriteLine("        /// </summary>");
        writer.WriteLine("        private const int PresentationEntrySize = sizeof(ushort) * (PresentationFormCount + 1);");
        writer.WriteLine();
        writer.WriteLine("        /// <summary>");
        writer.WriteLine("        /// The byte offset of the first presentation form in an entry.");
        writer.WriteLine("        /// </summary>");
        writer.WriteLine("        private const int FirstPresentationFormOffset = sizeof(ushort);");
        writer.WriteLine();
        writer.WriteLine("        /// <summary>");
        writer.WriteLine("        /// The number of bytes in one two-character ligature entry.");
        writer.WriteLine("        /// </summary>");
        writer.WriteLine("        public const int TwoCharacterLigatureEntrySize = sizeof(ushort) * 3;");
        writer.WriteLine();
        writer.WriteLine("        /// <summary>");
        writer.WriteLine("        /// The number of bytes in one three-character ligature entry.");
        writer.WriteLine("        /// </summary>");
        writer.WriteLine("        public const int ThreeCharacterLigatureEntrySize = sizeof(ushort) * 4;");
        writer.WriteLine();
        writer.WriteLine("        /// <summary>");
        writer.WriteLine("        /// Gets the requested presentation form for an Arabic character.");
        writer.WriteLine("        /// </summary>");
        writer.WriteLine("        /// <param name=\"codePoint\">The Arabic character.</param>");
        writer.WriteLine("        /// <param name=\"formIndex\">The zero-based form index: initial, medial, final, or isolated.</param>");
        writer.WriteLine("        /// <returns>The presentation-form character, or zero when no such form exists.</returns>");
        writer.WriteLine("        public static ushort GetPresentationForm(int codePoint, int formIndex)");
        writer.WriteLine("        {");
        writer.WriteLine("            ReadOnlySpan<byte> forms = PresentationForms;");
        writer.WriteLine("            int low = 0;");
        writer.WriteLine("            int high = (forms.Length / PresentationEntrySize) - 1;");
        writer.WriteLine("            while (low <= high)");
        writer.WriteLine("            {");
        writer.WriteLine("                int middle = low + ((high - low) >> 1);");
        writer.WriteLine("                int offset = middle * PresentationEntrySize;");
        writer.WriteLine("                ushort candidate = BinaryPrimitives.ReadUInt16LittleEndian(forms.Slice(offset, sizeof(ushort)));");
        writer.WriteLine("                if (codePoint < candidate)");
        writer.WriteLine("                {");
        writer.WriteLine("                    high = middle - 1;");
        writer.WriteLine("                }");
        writer.WriteLine("                else if (codePoint > candidate)");
        writer.WriteLine("                {");
        writer.WriteLine("                    low = middle + 1;");
        writer.WriteLine("                }");
        writer.WriteLine("                else");
        writer.WriteLine("                {");
        writer.WriteLine("                    int formOffset = offset + FirstPresentationFormOffset + (formIndex * sizeof(ushort));");
        writer.WriteLine("                    return BinaryPrimitives.ReadUInt16LittleEndian(forms.Slice(formOffset, sizeof(ushort)));");
        writer.WriteLine("                }");
        writer.WriteLine("            }");
        writer.WriteLine();
        writer.WriteLine("            return 0;");
        writer.WriteLine("        }");
        writer.WriteLine();

        WriteArabicPresentationForms(writer, forms);
        writer.WriteLine();
        WriteArabicLigatures(writer, "ThreeCharacterLigatures", "three-character", threeCharacterLigatures, true);
        writer.WriteLine();
        WriteArabicLigatures(writer, "TwoCharacterLigatures", "two-character", twoCharacterLigatures, false);
        writer.WriteLine();
        WriteArabicLigatures(writer, "MarkLigatures", "mark", markLigatures, false);

        writer.WriteLine("    }");
        writer.WriteLine("}");
    }

    /// <summary>
    /// Reads the Arabic presentation-form rows.
    /// </summary>
    /// <param name="source">The source table text.</param>
    /// <returns>The presentation-form rows in character order.</returns>
    private static List<(ushort CodePoint, ushort Initial, ushort Medial, ushort Final, ushort Isolated, string Name)> ReadArabicPresentationForms(string source)
    {
        List<(ushort CodePoint, ushort Initial, ushort Medial, ushort Final, ushort Isolated, string Name)> forms = [];
        foreach (Match match in ArabicPresentationFormRegex().Matches(source))
        {
            forms.Add((
                ParseHexUInt16(match.Groups["codePoint"].Value),
                ParseHexUInt16(match.Groups["initial"].Value),
                ParseHexUInt16(match.Groups["medial"].Value),
                ParseHexUInt16(match.Groups["final"].Value),
                ParseHexUInt16(match.Groups["isolated"].Value),
                match.Groups["name"].Value.Trim()));
        }

        if (forms.Count == 0)
        {
            throw new InvalidDataException("Found no Arabic presentation forms in the reference table.");
        }

        forms.Sort(static (left, right) => left.CodePoint.CompareTo(right.CodePoint));
        return forms;
    }

    /// <summary>
    /// Reads one required-ligature table.
    /// </summary>
    /// <param name="source">The source table text.</param>
    /// <param name="tableName">The table name.</param>
    /// <param name="componentCount">The number of characters following the first.</param>
    /// <returns>The ligature entries in source order.</returns>
    private static List<(ushort First, ushort Second, ushort Third, ushort Ligature, string Name)> ReadArabicLigatures(string source, string tableName, int componentCount)
    {
        int tableNameIndex = source.IndexOf($"{tableName}[]", StringComparison.Ordinal);
        int tableStart = tableNameIndex >= 0 ? source.IndexOf('{', tableNameIndex) : -1;
        int tableEnd = tableStart >= 0 ? source.IndexOf("\n};", tableStart, StringComparison.Ordinal) : -1;
        if (tableStart < 0 || tableEnd < 0)
        {
            throw new InvalidDataException($"Found no {tableName} in the reference table.");
        }

        string table = source[tableStart..tableEnd];
        List<(ushort First, ushort Second, ushort Third, ushort Ligature, string Name)> ligatures = [];
        foreach (Match setMatch in ArabicLigatureSetRegex().Matches(table))
        {
            ushort first = ParseHexUInt16(setMatch.Groups["first"].Value);
            foreach (Match ligatureMatch in ArabicLigatureRegex().Matches(setMatch.Groups["body"].Value))
            {
                MatchCollection componentMatches = ArabicLigatureComponentRegex().Matches(ligatureMatch.Groups["components"].Value);
                if (componentMatches.Count != componentCount)
                {
                    throw new InvalidDataException($"A {tableName} entry has {componentMatches.Count} components instead of {componentCount}.");
                }

                ushort second = ParseHexUInt16(componentMatches[0].Groups["value"].Value);
                ushort third = componentCount == 2 ? ParseHexUInt16(componentMatches[1].Groups["value"].Value) : (ushort)0;
                ligatures.Add((
                    first,
                    second,
                    third,
                    ParseHexUInt16(ligatureMatch.Groups["ligature"].Value),
                    ligatureMatch.Groups["name"].Value.Trim()));
            }
        }

        if (ligatures.Count == 0)
        {
            throw new InvalidDataException($"Found no entries in {tableName}.");
        }

        return ligatures;
    }

    /// <summary>
    /// Parses a two-byte hexadecimal character code.
    /// </summary>
    /// <param name="value">The hexadecimal digits.</param>
    /// <returns>The parsed character code.</returns>
    private static ushort ParseHexUInt16(string value)
        => ushort.Parse(value, NumberStyles.HexNumber, CultureInfo.InvariantCulture);

    /// <summary>
    /// Writes the presentation-form rows as packed little-endian bytes.
    /// </summary>
    /// <param name="writer">The output writer.</param>
    /// <param name="forms">The rows to write.</param>
    private static void WriteArabicPresentationForms(StreamWriter writer, List<(ushort CodePoint, ushort Initial, ushort Medial, ushort Final, ushort Isolated, string Name)> forms)
    {
        writer.WriteLine("        /// <summary>");
        writer.WriteLine("        /// The Arabic character rows in initial, medial, final, and isolated order.");
        writer.WriteLine("        /// </summary>");
        writer.WriteLine("        private static ReadOnlySpan<byte> PresentationForms =>");
        writer.WriteLine("        [");

        foreach ((ushort codePoint, ushort initial, ushort medial, ushort final, ushort isolated, string name) in forms)
        {
            string label = name.Length == 0 ? $"U+{codePoint:X4}" : $"U+{codePoint:X4} {name}";
            writer.WriteLine(
                $"            {FormatUInt16Bytes(codePoint)}, {FormatUInt16Bytes(initial)}, {FormatUInt16Bytes(medial)}, {FormatUInt16Bytes(final)}, {FormatUInt16Bytes(isolated)}, // {label}");
        }

        writer.WriteLine("        ];");
    }

    /// <summary>
    /// Writes a required-ligature table as packed little-endian bytes.
    /// </summary>
    /// <param name="writer">The output writer.</param>
    /// <param name="propertyName">The generated property name.</param>
    /// <param name="label">The human-readable table label.</param>
    /// <param name="ligatures">The entries to write.</param>
    /// <param name="includeThird">Whether each entry has a third character.</param>
    private static void WriteArabicLigatures(StreamWriter writer, string propertyName, string label, List<(ushort First, ushort Second, ushort Third, ushort Ligature, string Name)> ligatures, bool includeThird)
    {
        writer.WriteLine("        /// <summary>");
        writer.WriteLine($"        /// The {label} required ligatures.");
        writer.WriteLine("        /// </summary>");
        writer.WriteLine($"        public static ReadOnlySpan<byte> {propertyName} =>");
        writer.WriteLine("        [");

        foreach ((ushort first, ushort second, ushort third, ushort ligature, string name) in ligatures)
        {
            string components = includeThird
                ? $"{FormatUInt16Bytes(first)}, {FormatUInt16Bytes(second)}, {FormatUInt16Bytes(third)}"
                : $"{FormatUInt16Bytes(first)}, {FormatUInt16Bytes(second)}";

            writer.WriteLine($"            {components}, {FormatUInt16Bytes(ligature)}, // {name}");
        }

        writer.WriteLine("        ];");
    }

    /// <summary>
    /// Formats a two-byte value as little-endian byte literals.
    /// </summary>
    /// <param name="value">The value to format.</param>
    /// <returns>The two byte literals.</returns>
    private static string FormatUInt16Bytes(ushort value)
        => $"0x{value & LowByteMask:X2}, 0x{value >> HighByteShift:X2}";
}
