// Copyright (c) Six Labors.
// Licensed under the Six Labors Split License.

using UnicodeTrieGenerator.StateAutomation;
using Categories = SixLabors.Fonts.Unicode.Resources.IndicShapingData.Categories;
using KhmerCategories = SixLabors.Fonts.Unicode.Resources.IndicShapingData.KhmerCategories;

namespace UnicodeTrieGenerator;

/// <content>
/// Contains code to generate the Khmer syllable state machine.
/// </content>
public static partial class Generator
{
    /// <summary>
    /// Generates the Khmer syllable state machine from its grammar.
    /// </summary>
    /// <remarks>
    /// The grammar and category alphabet follow <c>tests/harfbuzz/src/hb-ot-shaper-khmer-machine.rl</c>,
    /// symbol <c>khmer_syllable_machine</c>. They are not derivable from the Unicode Character Database.
    /// </remarks>
    private static void GenerateKhmerShapingData()
    {
        KhmerCategories[] categories = Enum.GetValues<KhmerCategories>();
        Dictionary<string, int> symbols = new(categories.Length);
        int id = 0;

        foreach (KhmerCategories category in categories)
        {
            symbols[category.ToString()] = id++;
        }

        StateMachine machine = GetStateMachine("khmer", symbols);

        GenerateDataClass("KhmerShaping", null, null, machine, true);
        GenerateKhmerCategoryMap(categories);
    }

    /// <summary>
    /// Generates the sparse Khmer category to state-machine symbol mapping.
    /// </summary>
    /// <remarks>
    /// The symbol order follows <c>tests/harfbuzz/src/hb-ot-shaper-khmer-machine.rl</c>,
    /// symbol <c>khmer_syllable_machine</c>. It is not derivable from the Unicode Character Database.
    /// </remarks>
    /// <param name="categories">The state-machine categories in symbol order.</param>
    private static void GenerateKhmerCategoryMap(KhmerCategories[] categories)
    {
        Categories[] allCategories = Enum.GetValues<Categories>();
        int maxCategory = 0;
        foreach (Categories category in allCategories)
        {
            maxCategory = Math.Max(maxCategory, (int)category);
        }

        byte[] categoryToSymbolIds = new byte[maxCategory + 1];
        for (int symbolId = 0; symbolId < categories.Length; symbolId++)
        {
            categoryToSymbolIds[(int)categories[symbolId]] = checked((byte)symbolId);
        }

        using FileStream fileStream = GetStreamWriter("KhmerShapingCategoryMap.Generated.cs");
        using StreamWriter writer = new(fileStream);

        writer.WriteLine("// Copyright (c) Six Labors.");
        writer.WriteLine("// Licensed under the Six Labors Split License.");
        writer.WriteLine();
        writer.WriteLine("// <auto-generated />");
        writer.WriteLine("using System;");
        writer.WriteLine();
        writer.WriteLine("namespace SixLabors.Fonts.Unicode.Resources");
        writer.WriteLine("{");
        writer.WriteLine("    internal static partial class KhmerShapingData");
        writer.WriteLine("    {");
        writer.WriteLine("        /// <summary>");
        writer.WriteLine("        /// Maps sparse Khmer shaping categories to the state machine alphabet.");
        writer.WriteLine("        /// </summary>");
        writer.WriteLine("        /// <remarks>");
        writer.WriteLine("        /// The symbol order follows <c>tests/harfbuzz/src/hb-ot-shaper-khmer-machine.rl</c>,");
        writer.WriteLine("        /// symbol <c>khmer_syllable_machine</c>. It is not derivable from the Unicode Character Database.");
        writer.WriteLine("        /// </remarks>");
        writer.WriteLine("        public static ReadOnlySpan<byte> CategoryToSymbolIds =>");
        writer.WriteLine("        [");

        for (int category = 0; category < categoryToSymbolIds.Length; category++)
        {
            string label = Enum.GetName((Categories)category) ?? "Unassigned";
            writer.WriteLine($"            {categoryToSymbolIds[category]}, // {label}");
        }

        writer.WriteLine("        ];");
        writer.WriteLine("    }");
        writer.WriteLine("}");
    }
}
