// Copyright (c) Six Labors.
// Licensed under the Six Labors Split License.

using System.Text.RegularExpressions;
using SixLabors.Fonts.Unicode;

namespace UnicodeTrieGenerator;

/// <summary>
/// Generates Unicode Script_Extensions membership data used during shaping run itemization.
/// </summary>
public static partial class Generator
{
    /// <summary>
    /// Generates the Script_Extensions ranges from the Unicode Character Database.
    /// </summary>
    private static void GenerateScriptExtensionData()
    {
        Dictionary<string, ScriptClass> aliases = ReadScriptAliases();
        List<(int Start, int End, ScriptClass[] Scripts)> ranges = [];

        using StreamReader reader = GetStreamReader("ScriptExtensions.txt");
        string? line;
        while ((line = reader.ReadLine()) is not null)
        {
            Match match = UnicodePropertyRowRegex().Match(line);
            if (!match.Success)
            {
                continue;
            }

            int start = ParseHexInt(match.Groups[1].Value);
            int end = match.Groups[2].Success ? ParseHexInt(match.Groups[2].Value) : start;
            ScriptClass[] scripts = match.Groups[3].Value
                .Split(' ', StringSplitOptions.RemoveEmptyEntries)
                .Select(alias => aliases[alias])
                .Order()
                .ToArray();

            ranges.Add((start, end, scripts));
        }

        WriteScriptExtensionData(ranges);
    }

    /// <summary>
    /// Reads the short script aliases used by ScriptExtensions.txt.
    /// </summary>
    /// <returns>The script class keyed by its four-letter alias.</returns>
    private static Dictionary<string, ScriptClass> ReadScriptAliases()
    {
        Dictionary<string, ScriptClass> aliases = new(StringComparer.Ordinal);

        using StreamReader reader = GetStreamReader("PropertyValueAliases.txt");
        string? line;
        while ((line = reader.ReadLine()) is not null)
        {
            string[] fields = line.Split(';', StringSplitOptions.TrimEntries);
            if (fields.Length < 3 || fields[0] != "sc" || !ScriptMap.TryGetValue(fields[2], out ScriptClass script))
            {
                continue;
            }

            aliases.Add(fields[1], script);
        }

        return aliases;
    }

    /// <summary>
    /// Writes the Script_Extensions membership lookup.
    /// </summary>
    /// <param name="ranges">The code point ranges and scripts they support.</param>
    private static void WriteScriptExtensionData(List<(int Start, int End, ScriptClass[] Scripts)> ranges)
    {
        using FileStream fileStream = GetStreamWriter("ScriptExtensionData.Generated.cs");
        using StreamWriter writer = new(fileStream);

        writer.WriteLine("// Copyright (c) Six Labors.");
        writer.WriteLine("// Licensed under the Six Labors Split License.");
        writer.WriteLine();
        writer.WriteLine("// <auto-generated />");
        writer.WriteLine("namespace SixLabors.Fonts.Unicode.Resources");
        writer.WriteLine("{");
        writer.WriteLine("    /// <summary>");
        writer.WriteLine("    /// Unicode Script_Extensions membership for characters whose permitted scripts");
        writer.WriteLine("    /// differ from their Script property.");
        writer.WriteLine("    /// </summary>");
        writer.WriteLine("    internal static class ScriptExtensionData");
        writer.WriteLine("    {");
        writer.WriteLine("        /// <summary>");
        writer.WriteLine("        /// Determines whether the code point may be shaped as the requested script.");
        writer.WriteLine("        /// </summary>");
        writer.WriteLine("        /// <param name=\"codePoint\">The code point to test.</param>");
        writer.WriteLine("        /// <param name=\"script\">The candidate script.</param>");
        writer.WriteLine("        /// <returns>");
        writer.WriteLine("        /// <see langword=\"true\"/> when the script is listed for the code point;");
        writer.WriteLine("        /// otherwise, <see langword=\"false\"/>.");
        writer.WriteLine("        /// </returns>");
        writer.WriteLine("        public static bool Contains(CodePoint codePoint, ScriptClass script)");
        writer.WriteLine("        {");
        writer.WriteLine("            switch (codePoint.Value)");
        writer.WriteLine("            {");

        foreach ((int start, int end, ScriptClass[] scripts) in ranges)
        {
            string pattern = start == end ? $"0x{start:X}" : $">= 0x{start:X} and <= 0x{end:X}";
            writer.WriteLine($"                case {pattern}:");
            WriteScriptPattern(writer, scripts);
            writer.WriteLine();
        }

        writer.WriteLine("                default:");
        writer.WriteLine("                    return false;");
        writer.WriteLine("            }");
        writer.WriteLine("        }");
        writer.WriteLine("    }");
        writer.WriteLine("}");
    }

    /// <summary>
    /// Writes a wrapped C# pattern matching any script in the set.
    /// </summary>
    /// <param name="writer">The generated source writer.</param>
    /// <param name="scripts">The scripts in the set.</param>
    private static void WriteScriptPattern(StreamWriter writer, ScriptClass[] scripts)
    {
        const int LineLength = 120;
        const string FirstPrefix = "                    return script is ";
        const string ContinuationPrefix = "                        or ";

        string line = FirstPrefix;
        for (int i = 0; i < scripts.Length; i++)
        {
            string script = $"ScriptClass.{scripts[i]}";
            string separator = i == 0 ? string.Empty : " or ";
            if (line.Length + separator.Length + script.Length > LineLength)
            {
                writer.WriteLine(line);
                line = ContinuationPrefix + script;
                continue;
            }

            line += separator + script;
        }

        writer.WriteLine(line + ";");
    }
}
