// Copyright (c) Six Labors.
// Licensed under the Six Labors Split License.

// <auto-generated />
using System;

namespace SixLabors.Fonts.Unicode.Resources
{
    internal static partial class KhmerShapingData
    {
        /// <summary>
        /// Maps sparse Khmer shaping categories to the state machine alphabet.
        /// </summary>
        /// <remarks>
        /// The symbol order follows <c>tests/harfbuzz/src/hb-ot-shaper-khmer-machine.rl</c>,
        /// symbol <c>khmer_syllable_machine</c>. It is not derivable from the Unicode Character Database.
        /// </remarks>
        public static ReadOnlySpan<byte> CategoryToSymbolIds =>
        [
            0, // X
            1, // C
            2, // V
            0, // N
            3, // H
            4, // ZWNJ
            5, // ZWJ
            0, // M
            0, // SM
            0, // A
            6, // Placeholder
            7, // Dotted_Circle
            0, // RS
            0, // MPst
            0, // Repha
            8, // Ra
            0, // CM
            0, // Symbol
            0, // CS
            0, // Unassigned
            9, // VAbv
            10, // VBlw
            11, // VPre
            12, // VPst
            0, // Unassigned
            13, // Robatic
            14, // Xgroup
            15, // Ygroup
            0, // Unassigned
            0, // Unassigned
            0, // Unassigned
            0, // Unassigned
            0, // As
            0, // Unassigned
            0, // Unassigned
            0, // MH
            0, // MR
            0, // MW
            0, // MY
            0, // PT
            0, // VS
            0, // ML
            0, // Unassigned
            0, // Unassigned
            0, // Unassigned
            0, // Unassigned
            0, // Unassigned
            0, // Unassigned
            0, // Unassigned
            0, // Unassigned
            0, // Unassigned
            0, // Unassigned
            0, // Unassigned
            0, // Unassigned
            0, // Unassigned
            0, // Unassigned
            0, // Unassigned
            0, // SMPst
        ];
    }
}
