// Copyright (c) Six Labors.
// Licensed under the Six Labors Split License.

// <auto-generated />
using System;

namespace SixLabors.Fonts.Unicode.Resources
{
    /// <summary>
    /// The classes that order a mark against the marks around it.
    /// </summary>
    internal static class MarkOrderingData
    {
        /// <summary>
        /// Gets the order given to the canonical combining class at each index. Every
        /// class orders as itself except where a script draws its marks in an order its
        /// assigned classes do not give, and those are renumbered so that one sort
        /// leaves the marks of every script in the order they are drawn.
        /// </summary>
        public static ReadOnlySpan<byte> Classes => new byte[]
        {
            0,  // ccc 0, Not_Reordered
            1,  // ccc 1, Overlay
            2, 3, 4, 5, 6,  // ccc 2..6
            7,  // ccc 7, Nukta
            8,  // ccc 8, Kana_Voicing
            9,  // ccc 9, Virama

            // Hebrew.
            22,  // ccc 10, sheva
            15,  // ccc 11, hataf segol
            16,  // ccc 12, hataf patah
            17,  // ccc 13, hataf qamats
            23,  // ccc 14, hiriq
            18,  // ccc 15, tsere
            19,  // ccc 16, segol
            20,  // ccc 17, patah
            21,  // ccc 18, qamats & qamats qatan
            14,  // ccc 19, holam & holam haser for vav
            24,  // ccc 20, qubuts
            12,  // ccc 21, dagesh
            25,  // ccc 22, meteg
            13,  // ccc 23, rafe
            10,  // ccc 24, shin dot
            11,  // ccc 25, sin dot
            26,  // ccc 26, point varika

            // Arabic.
            28,  // ccc 27, fathatan
            29,  // ccc 28, dammatan
            30,  // ccc 29, kasratan
            31,  // ccc 30, fatha
            32,  // ccc 31, damma
            33,  // ccc 32, kasra
            27,  // ccc 33, shadda
            34,  // ccc 34, sukun
            35,  // ccc 35, superscript alef

            // Syriac.
            36,  // ccc 36, superscript alaph
            37, 38, 39, 40, 41, 42, 43, 44, 45, 46,  // ccc 37..46
            47, 48, 49, 50, 51, 52, 53, 54, 55, 56,  // ccc 47..56
            57, 58, 59, 60, 61, 62, 63, 64, 65, 66,  // ccc 57..66
            67, 68, 69, 70, 71, 72, 73, 74, 75, 76,  // ccc 67..76
            77, 78, 79, 80, 81, 82, 83,  // ccc 77..83

            // Telugu.
            4,  // ccc 84, length mark
            85, 86, 87, 88, 89, 90,  // ccc 85..90
            5,  // ccc 91, ai length mark
            92, 93, 94, 95, 96, 97, 98, 99, 100, 101,  // ccc 92..101
            102,  // ccc 102..102

            // Thai.
            3,  // ccc 103, sara u / sara uu
            104, 105, 106, 107, 108, 109, 110, 111, 112, 113,  // ccc 104..113
            114, 115, 116, 117,  // ccc 114..117

            // Lao.
            118,  // ccc 118, sign u / sign uu
            119, 120, 121, 122, 123, 124, 125, 126, 127, 128,  // ccc 119..128

            // Tibetan.
            129,  // ccc 129, sign aa
            132,  // ccc 130, sign i
            131,  // ccc 131..131
            131,  // ccc 132, sign u
            133, 134, 135, 136, 137, 138, 139, 140, 141, 142,  // ccc 133..142
            143, 144, 145, 146, 147, 148, 149, 150, 151, 152,  // ccc 143..152
            153, 154, 155, 156, 157, 158, 159, 160, 161, 162,  // ccc 153..162
            163, 164, 165, 166, 167, 168, 169, 170, 171, 172,  // ccc 163..172
            173, 174, 175, 176, 177, 178, 179, 180, 181, 182,  // ccc 173..182
            183, 184, 185, 186, 187, 188, 189, 190, 191, 192,  // ccc 183..192
            193, 194, 195, 196, 197, 198, 199,  // ccc 193..199
            200,  // ccc 200, Attached_Below_Left
            201,  // ccc 201..201
            202,  // ccc 202, Attached_Below
            203, 204, 205, 206, 207, 208, 209, 210, 211, 212,  // ccc 203..212
            213,  // ccc 213..213
            214,  // ccc 214, Attached_Above
            215,  // ccc 215..215
            216,  // ccc 216, Attached_Above_Right
            217,  // ccc 217..217
            218,  // ccc 218, Below_Left
            219,  // ccc 219..219
            220,  // ccc 220, Below
            221,  // ccc 221..221
            222,  // ccc 222, Below_Right
            223,  // ccc 223..223
            224,  // ccc 224, Left
            225,  // ccc 225..225
            226,  // ccc 226, Right
            227,  // ccc 227..227
            228,  // ccc 228, Above_Left
            229,  // ccc 229..229
            230,  // ccc 230, Above
            231,  // ccc 231..231
            232,  // ccc 232, Above_Right
            233,  // ccc 233, Double_Below
            234,  // ccc 234, Double_Above
            235, 236, 237, 238, 239,  // ccc 235..239
            240,  // ccc 240, Iota_Subscript
            241, 242, 243, 244, 245, 246, 247, 248, 249, 250,  // ccc 241..250
            251, 252, 253, 254,  // ccc 251..254
            255,  // ccc 255, Invalid
        };

        /// <summary>
        /// Tries to get the order of a character that orders by where it is drawn rather
        /// than by its class.
        /// </summary>
        /// <remarks>
        /// Written as a switch rather than a table because there are only a handful, and
        /// because a span of anything wider than a byte is a fresh array on every access:
        /// a table here would allocate once per character shaped.
        /// </remarks>
        /// <param name="codePoint">The code point to look up.</param>
        /// <param name="order">When this method returns, contains the order.</param>
        /// <returns><see langword="true"/> when the character orders by where it is drawn.</returns>
        public static bool TryGetOverride(uint codePoint, out byte order)
        {
            switch (codePoint)
            {
                // TIBETAN MARK TSA -PHRU
                case 0x0F39:
                    order = 127;
                    return true;

                // TIBETAN SYMBOL PADMA GDAN
                case 0x0FC6:
                    order = 254;
                    return true;

                // TAI THAM SIGN SAKOT
                case 0x1A60:
                    order = 254;
                    return true;

                default:
                    order = 0;
                    return false;
            }
        }
    }
}
