// Copyright (c) Six Labors.
// Licensed under the Six Labors Split License.

// <auto-generated />
namespace SixLabors.Fonts.Unicode.Resources
{
    /// <summary>
    /// The direction each script is written in when it is set horizontally.
    /// </summary>
    internal static class ScriptDirectionData
    {
        /// <summary>
        /// Gets the direction the given script is written in. A script the standard writes
        /// left to right is not listed here and answers with that direction.
        /// </summary>
        /// <param name="script">The script to look up.</param>
        /// <returns>The direction the script is written in.</returns>
        public static ScriptHorizontalDirection GetDirection(ScriptClass script)
        {
            switch (script)
            {
                case ScriptClass.Adlam:
                case ScriptClass.Arabic:
                case ScriptClass.Avestan:
                case ScriptClass.Chorasmian:
                case ScriptClass.Cypriot:
                case ScriptClass.Elymaic:
                case ScriptClass.Garay:
                case ScriptClass.HanifiRohingya:
                case ScriptClass.Hatran:
                case ScriptClass.Hebrew:
                case ScriptClass.ImperialAramaic:
                case ScriptClass.InscriptionalPahlavi:
                case ScriptClass.InscriptionalParthian:
                case ScriptClass.Kharoshthi:
                case ScriptClass.Lydian:
                case ScriptClass.Mandaic:
                case ScriptClass.Manichaean:
                case ScriptClass.MendeKikakui:
                case ScriptClass.MeroiticCursive:
                case ScriptClass.MeroiticHieroglyphs:
                case ScriptClass.Nabataean:
                case ScriptClass.Nko:
                case ScriptClass.OldNorthArabian:
                case ScriptClass.OldSogdian:
                case ScriptClass.OldSouthArabian:
                case ScriptClass.OldTurkic:
                case ScriptClass.OldUyghur:
                case ScriptClass.Palmyrene:
                case ScriptClass.Phoenician:
                case ScriptClass.PsalterPahlavi:
                case ScriptClass.Samaritan:
                case ScriptClass.Sidetic:
                case ScriptClass.Sogdian:
                case ScriptClass.Syriac:
                case ScriptClass.Thaana:
                case ScriptClass.Yezidi:
                    return ScriptHorizontalDirection.RightToLeft;

                case ScriptClass.OldHungarian:
                case ScriptClass.OldItalic:
                case ScriptClass.Runic:
                case ScriptClass.Tifinagh:
                    return ScriptHorizontalDirection.Either;

                default:
                    return ScriptHorizontalDirection.LeftToRight;
            }
        }
    }
}
