// Copyright (c) Six Labors.
// Licensed under the Six Labors Split License.

// <auto-generated />
namespace SixLabors.Fonts.Unicode.Resources
{
    /// <summary>
    /// Unicode Script_Extensions membership for characters whose permitted scripts
    /// differ from their Script property.
    /// </summary>
    internal static class ScriptExtensionData
    {
        /// <summary>
        /// Determines whether the code point may be shaped as the requested script.
        /// </summary>
        /// <param name="codePoint">The code point to test.</param>
        /// <param name="script">The candidate script.</param>
        /// <returns>
        /// <see langword="true"/> when the script is listed for the code point;
        /// otherwise, <see langword="false"/>.
        /// </returns>
        public static bool Contains(CodePoint codePoint, ScriptClass script)
        {
            switch (codePoint.Value)
            {
                case 0xB7:
                    return script is ScriptClass.Avestan or ScriptClass.Carian or ScriptClass.Coptic
                        or ScriptClass.Duployan or ScriptClass.Elbasan or ScriptClass.Georgian or ScriptClass.Glagolitic
                        or ScriptClass.GunjalaGondi or ScriptClass.Gothic or ScriptClass.Greek or ScriptClass.Han
                        or ScriptClass.Latin or ScriptClass.Lydian or ScriptClass.Mahajani or ScriptClass.OldPermic
                        or ScriptClass.Shavian;

                case 0x2BC:
                    return script is ScriptClass.Bengali or ScriptClass.Cyrillic or ScriptClass.Devanagari
                        or ScriptClass.Latin or ScriptClass.Lisu or ScriptClass.Thai or ScriptClass.Toto;

                case 0x2C7:
                    return script is ScriptClass.Bopomofo or ScriptClass.Latin;

                case >= 0x2C9 and <= 0x2CB:
                    return script is ScriptClass.Bopomofo or ScriptClass.Latin;

                case 0x2CD:
                    return script is ScriptClass.Latin or ScriptClass.Lisu;

                case 0x2D7:
                    return script is ScriptClass.Latin or ScriptClass.Thai;

                case 0x2D9:
                    return script is ScriptClass.Bopomofo or ScriptClass.Latin;

                case 0x300:
                    return script is ScriptClass.Cherokee or ScriptClass.Coptic or ScriptClass.Cyrillic
                        or ScriptClass.Greek or ScriptClass.Latin or ScriptClass.OldPermic or ScriptClass.TaiLe
                        or ScriptClass.Sunuwar;

                case 0x301:
                    return script is ScriptClass.Cherokee or ScriptClass.Cyrillic or ScriptClass.Greek
                        or ScriptClass.Latin or ScriptClass.Osage or ScriptClass.TaiLe or ScriptClass.Sunuwar
                        or ScriptClass.Todhri;

                case 0x302:
                    return script is ScriptClass.Cherokee or ScriptClass.Cyrillic or ScriptClass.Latin
                        or ScriptClass.Tifinagh;

                case 0x303:
                    return script is ScriptClass.Glagolitic or ScriptClass.Latin or ScriptClass.Syriac
                        or ScriptClass.Thai or ScriptClass.Sunuwar;

                case 0x304:
                    return script is ScriptClass.CaucasianAlbanian or ScriptClass.Cherokee or ScriptClass.Coptic
                        or ScriptClass.Cyrillic or ScriptClass.Gothic or ScriptClass.Greek or ScriptClass.Latin
                        or ScriptClass.Osage or ScriptClass.Syriac or ScriptClass.Tifinagh or ScriptClass.Todhri;

                case 0x305:
                    return script is ScriptClass.Coptic or ScriptClass.Elbasan or ScriptClass.Glagolitic
                        or ScriptClass.Gothic or ScriptClass.Katakana or ScriptClass.Latin;

                case 0x306:
                    return script is ScriptClass.Cyrillic or ScriptClass.Greek or ScriptClass.Latin
                        or ScriptClass.OldPermic or ScriptClass.Tifinagh;

                case 0x307:
                    return script is ScriptClass.Coptic or ScriptClass.Duployan or ScriptClass.Hebrew
                        or ScriptClass.Latin or ScriptClass.OldPermic or ScriptClass.Syriac or ScriptClass.TaiLe
                        or ScriptClass.Tifinagh or ScriptClass.Todhri;

                case 0x308:
                    return script is ScriptClass.Armenian or ScriptClass.Cyrillic or ScriptClass.Duployan
                        or ScriptClass.Gothic or ScriptClass.Greek or ScriptClass.Hebrew or ScriptClass.Latin
                        or ScriptClass.OldPermic or ScriptClass.Syriac or ScriptClass.TaiLe or ScriptClass.Tifinagh;

                case 0x309:
                    return script is ScriptClass.Latin or ScriptClass.Tifinagh;

                case 0x30A:
                    return script is ScriptClass.Duployan or ScriptClass.Latin or ScriptClass.Syriac;

                case 0x30B:
                    return script is ScriptClass.Cherokee or ScriptClass.Cyrillic or ScriptClass.Latin
                        or ScriptClass.Osage;

                case 0x30C:
                    return script is ScriptClass.Cherokee or ScriptClass.Latin or ScriptClass.TaiLe;

                case 0x30D:
                    return script is ScriptClass.Latin or ScriptClass.Sunuwar;

                case 0x30E:
                    return script is ScriptClass.Ethiopic or ScriptClass.Latin;

                case 0x310:
                    return script is ScriptClass.Latin or ScriptClass.Sunuwar;

                case 0x311:
                    return script is ScriptClass.Cyrillic or ScriptClass.Latin or ScriptClass.Todhri;

                case 0x313:
                    return script is ScriptClass.Greek or ScriptClass.Latin or ScriptClass.OldPermic
                        or ScriptClass.Todhri;

                case 0x323:
                    return script is ScriptClass.Cherokee or ScriptClass.Duployan or ScriptClass.Katakana
                        or ScriptClass.Latin or ScriptClass.Syriac or ScriptClass.Tifinagh;

                case 0x324:
                    return script is ScriptClass.Cherokee or ScriptClass.Duployan or ScriptClass.Latin
                        or ScriptClass.Syriac;

                case 0x325:
                    return script is ScriptClass.Latin or ScriptClass.Syriac;

                case 0x32D:
                    return script is ScriptClass.Latin or ScriptClass.Syriac or ScriptClass.Sunuwar;

                case 0x32E:
                    return script is ScriptClass.Latin or ScriptClass.Syriac;

                case 0x330:
                    return script is ScriptClass.Cherokee or ScriptClass.Latin or ScriptClass.Syriac;

                case 0x331:
                    return script is ScriptClass.CaucasianAlbanian or ScriptClass.Cherokee or ScriptClass.Gothic
                        or ScriptClass.Latin or ScriptClass.Syriac or ScriptClass.Thai or ScriptClass.Sunuwar;

                case 0x342:
                    return script is ScriptClass.Greek;

                case 0x345:
                    return script is ScriptClass.Greek;

                case 0x358:
                    return script is ScriptClass.Latin or ScriptClass.Osage;

                case 0x35E:
                    return script is ScriptClass.CaucasianAlbanian or ScriptClass.Latin or ScriptClass.Todhri;

                case >= 0x363 and <= 0x36F:
                    return script is ScriptClass.Latin;

                case 0x374:
                    return script is ScriptClass.Coptic or ScriptClass.Greek;

                case 0x375:
                    return script is ScriptClass.Coptic or ScriptClass.Greek;

                case 0x483:
                    return script is ScriptClass.Cyrillic or ScriptClass.OldPermic;

                case 0x484:
                    return script is ScriptClass.Cyrillic or ScriptClass.Glagolitic;

                case >= 0x485 and <= 0x486:
                    return script is ScriptClass.Cyrillic or ScriptClass.Latin;

                case 0x487:
                    return script is ScriptClass.Cyrillic or ScriptClass.Glagolitic;

                case 0x589:
                    return script is ScriptClass.Armenian or ScriptClass.Georgian or ScriptClass.Glagolitic;

                case 0x60C:
                    return script is ScriptClass.Arabic or ScriptClass.Nko or ScriptClass.HanifiRohingya
                        or ScriptClass.Syriac or ScriptClass.Thaana or ScriptClass.Yezidi or ScriptClass.Garay;

                case 0x61B:
                    return script is ScriptClass.Arabic or ScriptClass.Nko or ScriptClass.HanifiRohingya
                        or ScriptClass.Syriac or ScriptClass.Thaana or ScriptClass.Yezidi or ScriptClass.Garay;

                case 0x61C:
                    return script is ScriptClass.Arabic or ScriptClass.Syriac or ScriptClass.Thaana;

                case 0x61F:
                    return script is ScriptClass.Adlam or ScriptClass.Arabic or ScriptClass.Nko
                        or ScriptClass.HanifiRohingya or ScriptClass.Syriac or ScriptClass.Thaana or ScriptClass.Yezidi
                        or ScriptClass.Garay;

                case 0x640:
                    return script is ScriptClass.Adlam or ScriptClass.Arabic or ScriptClass.Mandaic
                        or ScriptClass.Manichaean or ScriptClass.OldUyghur or ScriptClass.PsalterPahlavi
                        or ScriptClass.HanifiRohingya or ScriptClass.Sogdian or ScriptClass.Syriac;

                case >= 0x64B and <= 0x655:
                    return script is ScriptClass.Arabic or ScriptClass.Syriac;

                case >= 0x660 and <= 0x669:
                    return script is ScriptClass.Arabic or ScriptClass.Thaana or ScriptClass.Yezidi;

                case 0x670:
                    return script is ScriptClass.Arabic or ScriptClass.Syriac;

                case 0x6D4:
                    return script is ScriptClass.Arabic or ScriptClass.HanifiRohingya;

                case 0x951:
                    return script is ScriptClass.Bengali or ScriptClass.Devanagari or ScriptClass.Grantha
                        or ScriptClass.Gujarati or ScriptClass.Gurmukhi or ScriptClass.Kannada or ScriptClass.Latin
                        or ScriptClass.Malayalam or ScriptClass.Nandinagari or ScriptClass.Newa or ScriptClass.Oriya
                        or ScriptClass.Sharada or ScriptClass.Tamil or ScriptClass.Telugu or ScriptClass.Tirhuta;

                case 0x952:
                    return script is ScriptClass.Bengali or ScriptClass.Devanagari or ScriptClass.Grantha
                        or ScriptClass.Gujarati or ScriptClass.Gurmukhi or ScriptClass.Kannada or ScriptClass.Latin
                        or ScriptClass.Malayalam or ScriptClass.Newa or ScriptClass.Oriya or ScriptClass.Tamil
                        or ScriptClass.Telugu or ScriptClass.Tirhuta;

                case 0x964:
                    return script is ScriptClass.Bengali or ScriptClass.Devanagari or ScriptClass.Dogra
                        or ScriptClass.GunjalaGondi or ScriptClass.MasaramGondi or ScriptClass.Grantha
                        or ScriptClass.Gujarati or ScriptClass.Gurmukhi or ScriptClass.Kannada or ScriptClass.Mahajani
                        or ScriptClass.Malayalam or ScriptClass.Nandinagari or ScriptClass.Oriya
                        or ScriptClass.Khudawadi or ScriptClass.Sinhala or ScriptClass.SylotiNagri or ScriptClass.Takri
                        or ScriptClass.Tamil or ScriptClass.Telugu or ScriptClass.Tirhuta or ScriptClass.OlOnal;

                case 0x965:
                    return script is ScriptClass.Bengali or ScriptClass.Devanagari or ScriptClass.Dogra
                        or ScriptClass.GunjalaGondi or ScriptClass.MasaramGondi or ScriptClass.Grantha
                        or ScriptClass.Gujarati or ScriptClass.Gurmukhi or ScriptClass.Kannada or ScriptClass.Limbu
                        or ScriptClass.Mahajani or ScriptClass.Malayalam or ScriptClass.Nandinagari or ScriptClass.Oriya
                        or ScriptClass.Khudawadi or ScriptClass.Sinhala or ScriptClass.SylotiNagri or ScriptClass.Takri
                        or ScriptClass.Tamil or ScriptClass.Telugu or ScriptClass.Tirhuta or ScriptClass.GurungKhema
                        or ScriptClass.OlOnal;

                case >= 0x966 and <= 0x96F:
                    return script is ScriptClass.Devanagari or ScriptClass.Dogra or ScriptClass.Kaithi
                        or ScriptClass.Mahajani;

                case >= 0x9E6 and <= 0x9EF:
                    return script is ScriptClass.Bengali or ScriptClass.Chakma or ScriptClass.SylotiNagri;

                case >= 0xA66 and <= 0xA6F:
                    return script is ScriptClass.Gurmukhi or ScriptClass.Multani;

                case >= 0xAE6 and <= 0xAEF:
                    return script is ScriptClass.Gujarati or ScriptClass.Khojki;

                case >= 0xBE6 and <= 0xBEF:
                    return script is ScriptClass.Grantha or ScriptClass.Tamil;

                case >= 0xBF0 and <= 0xBF2:
                    return script is ScriptClass.Grantha or ScriptClass.Tamil;

                case 0xBF3:
                    return script is ScriptClass.Grantha or ScriptClass.Tamil;

                case >= 0xCE6 and <= 0xCEF:
                    return script is ScriptClass.Kannada or ScriptClass.Nandinagari or ScriptClass.TuluTigalari;

                case >= 0x1040 and <= 0x1049:
                    return script is ScriptClass.Chakma or ScriptClass.Myanmar or ScriptClass.TaiLe;

                case 0x10FB:
                    return script is ScriptClass.Georgian or ScriptClass.Glagolitic or ScriptClass.Latin;

                case >= 0x16EB and <= 0x16ED:
                    return script is ScriptClass.Runic;

                case >= 0x1735 and <= 0x1736:
                    return script is ScriptClass.Buhid or ScriptClass.Hanunoo or ScriptClass.Tagbanwa
                        or ScriptClass.Tagalog;

                case >= 0x1802 and <= 0x1803:
                    return script is ScriptClass.Mongolian or ScriptClass.PhagsPa;

                case 0x1805:
                    return script is ScriptClass.Mongolian or ScriptClass.PhagsPa;

                case 0x1CD0:
                    return script is ScriptClass.Bengali or ScriptClass.Devanagari or ScriptClass.Grantha
                        or ScriptClass.Kannada;

                case 0x1CD1:
                    return script is ScriptClass.Devanagari;

                case 0x1CD2:
                    return script is ScriptClass.Bengali or ScriptClass.Devanagari or ScriptClass.Grantha
                        or ScriptClass.Kannada;

                case 0x1CD3:
                    return script is ScriptClass.Devanagari or ScriptClass.Grantha or ScriptClass.Kannada;

                case 0x1CD4:
                    return script is ScriptClass.Devanagari;

                case 0x1CD5:
                    return script is ScriptClass.Bengali or ScriptClass.Devanagari or ScriptClass.Newa
                        or ScriptClass.Telugu or ScriptClass.Tirhuta;

                case 0x1CD6:
                    return script is ScriptClass.Bengali or ScriptClass.Devanagari or ScriptClass.Telugu;

                case 0x1CD7:
                    return script is ScriptClass.Devanagari or ScriptClass.Newa or ScriptClass.Sharada;

                case 0x1CD8:
                    return script is ScriptClass.Bengali or ScriptClass.Devanagari or ScriptClass.Newa
                        or ScriptClass.Telugu;

                case 0x1CD9:
                    return script is ScriptClass.Devanagari or ScriptClass.Sharada;

                case 0x1CDA:
                    return script is ScriptClass.Devanagari or ScriptClass.Kannada or ScriptClass.Malayalam
                        or ScriptClass.Oriya or ScriptClass.Tamil or ScriptClass.Telugu;

                case 0x1CDB:
                    return script is ScriptClass.Devanagari;

                case >= 0x1CDC and <= 0x1CDD:
                    return script is ScriptClass.Devanagari or ScriptClass.Sharada;

                case >= 0x1CDE and <= 0x1CDF:
                    return script is ScriptClass.Devanagari;

                case 0x1CE0:
                    return script is ScriptClass.Devanagari or ScriptClass.Sharada;

                case 0x1CE1:
                    return script is ScriptClass.Bengali or ScriptClass.Devanagari;

                case 0x1CE2:
                    return script is ScriptClass.Devanagari or ScriptClass.Newa or ScriptClass.Tirhuta;

                case >= 0x1CE3 and <= 0x1CE8:
                    return script is ScriptClass.Devanagari;

                case 0x1CE9:
                    return script is ScriptClass.Devanagari or ScriptClass.Nandinagari or ScriptClass.Newa;

                case 0x1CEA:
                    return script is ScriptClass.Bengali or ScriptClass.Devanagari or ScriptClass.Sharada;

                case 0x1CEB:
                    return script is ScriptClass.Devanagari or ScriptClass.Newa;

                case 0x1CEC:
                    return script is ScriptClass.Devanagari;

                case 0x1CED:
                    return script is ScriptClass.Bengali or ScriptClass.Devanagari or ScriptClass.Newa
                        or ScriptClass.Sharada;

                case >= 0x1CEE and <= 0x1CF1:
                    return script is ScriptClass.Devanagari;

                case 0x1CF2:
                    return script is ScriptClass.Bengali or ScriptClass.Devanagari or ScriptClass.Grantha
                        or ScriptClass.Kannada or ScriptClass.Malayalam or ScriptClass.Nandinagari or ScriptClass.Oriya
                        or ScriptClass.Sinhala or ScriptClass.Telugu or ScriptClass.Tirhuta or ScriptClass.TuluTigalari;

                case 0x1CF3:
                    return script is ScriptClass.Devanagari or ScriptClass.Grantha;

                case 0x1CF4:
                    return script is ScriptClass.Devanagari or ScriptClass.Grantha or ScriptClass.Kannada
                        or ScriptClass.TuluTigalari;

                case >= 0x1CF5 and <= 0x1CF6:
                    return script is ScriptClass.Bengali or ScriptClass.Devanagari;

                case 0x1CF7:
                    return script is ScriptClass.Bengali;

                case >= 0x1CF8 and <= 0x1CF9:
                    return script is ScriptClass.Devanagari or ScriptClass.Grantha;

                case 0x1CFA:
                    return script is ScriptClass.Nandinagari;

                case >= 0x1DC0 and <= 0x1DC1:
                    return script is ScriptClass.Greek;

                case 0x1DF8:
                    return script is ScriptClass.Cyrillic or ScriptClass.Latin or ScriptClass.Syriac;

                case 0x1DFA:
                    return script is ScriptClass.Syriac;

                case 0x202F:
                    return script is ScriptClass.Latin or ScriptClass.Mongolian or ScriptClass.PhagsPa;

                case 0x204F:
                    return script is ScriptClass.Adlam or ScriptClass.Arabic;

                case 0x205A:
                    return script is ScriptClass.Carian or ScriptClass.Georgian or ScriptClass.Glagolitic
                        or ScriptClass.OldHungarian or ScriptClass.Lycian or ScriptClass.OldTurkic;

                case 0x205D:
                    return script is ScriptClass.Carian or ScriptClass.Greek or ScriptClass.OldHungarian
                        or ScriptClass.MeroiticHieroglyphs;

                case 0x20F0:
                    return script is ScriptClass.Devanagari or ScriptClass.Grantha or ScriptClass.Latin;

                case 0x2E17:
                    return script is ScriptClass.Coptic or ScriptClass.Latin;

                case 0x2E30:
                    return script is ScriptClass.Avestan or ScriptClass.OldTurkic;

                case 0x2E31:
                    return script is ScriptClass.Avestan or ScriptClass.Carian or ScriptClass.Georgian
                        or ScriptClass.OldHungarian or ScriptClass.Kaithi or ScriptClass.Lydian or ScriptClass.Samaritan;

                case 0x2E3C:
                    return script is ScriptClass.Duployan;

                case 0x2E41:
                    return script is ScriptClass.Adlam or ScriptClass.Arabic or ScriptClass.OldHungarian;

                case 0x2E43:
                    return script is ScriptClass.Cyrillic or ScriptClass.Glagolitic;

                case >= 0x2FF0 and <= 0x2FFF:
                    return script is ScriptClass.Han or ScriptClass.Tangut;

                case 0x3001:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana or ScriptClass.Mongolian or ScriptClass.Yi;

                case 0x3002:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana or ScriptClass.Mongolian or ScriptClass.PhagsPa
                        or ScriptClass.Yi;

                case 0x3003:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana;

                case 0x3006:
                    return script is ScriptClass.Han;

                case 0x3008:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana or ScriptClass.Mongolian or ScriptClass.Tibetan
                        or ScriptClass.Yi;

                case 0x3009:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana or ScriptClass.Mongolian or ScriptClass.Tibetan
                        or ScriptClass.Yi;

                case 0x300A:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana or ScriptClass.Lisu or ScriptClass.Mongolian
                        or ScriptClass.Tibetan or ScriptClass.Yi;

                case 0x300B:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana or ScriptClass.Lisu or ScriptClass.Mongolian
                        or ScriptClass.Tibetan or ScriptClass.Yi;

                case 0x300C:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana or ScriptClass.Yi;

                case 0x300D:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana or ScriptClass.Yi;

                case 0x300E:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana or ScriptClass.Yi;

                case 0x300F:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana or ScriptClass.Yi;

                case 0x3010:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana or ScriptClass.Yi;

                case 0x3011:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana or ScriptClass.Yi;

                case 0x3013:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana;

                case 0x3014:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana or ScriptClass.Yi;

                case 0x3015:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana or ScriptClass.Yi;

                case 0x3016:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana or ScriptClass.Yi;

                case 0x3017:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana or ScriptClass.Yi;

                case 0x3018:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana or ScriptClass.Yi;

                case 0x3019:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana or ScriptClass.Yi;

                case 0x301A:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana or ScriptClass.Yi;

                case 0x301B:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana or ScriptClass.Yi;

                case 0x301C:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana;

                case 0x301D:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana;

                case >= 0x301E and <= 0x301F:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana;

                case >= 0x302A and <= 0x302D:
                    return script is ScriptClass.Bopomofo or ScriptClass.Han;

                case 0x3030:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana;

                case >= 0x3031 and <= 0x3035:
                    return script is ScriptClass.Hiragana or ScriptClass.Katakana;

                case 0x3037:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana;

                case 0x303C:
                    return script is ScriptClass.Han or ScriptClass.Hiragana or ScriptClass.Katakana;

                case 0x303D:
                    return script is ScriptClass.Han or ScriptClass.Hiragana or ScriptClass.Katakana;

                case >= 0x303E and <= 0x303F:
                    return script is ScriptClass.Han;

                case >= 0x3099 and <= 0x309A:
                    return script is ScriptClass.Hiragana or ScriptClass.Katakana;

                case >= 0x309B and <= 0x309C:
                    return script is ScriptClass.Hiragana or ScriptClass.Katakana;

                case 0x30A0:
                    return script is ScriptClass.Hiragana or ScriptClass.Katakana;

                case 0x30FB:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana or ScriptClass.Yi;

                case 0x30FC:
                    return script is ScriptClass.Hiragana or ScriptClass.Katakana;

                case >= 0x3190 and <= 0x3191:
                    return script is ScriptClass.Han;

                case >= 0x3192 and <= 0x3195:
                    return script is ScriptClass.Han;

                case >= 0x3196 and <= 0x319F:
                    return script is ScriptClass.Han;

                case >= 0x31C0 and <= 0x31E5:
                    return script is ScriptClass.Han;

                case 0x31EF:
                    return script is ScriptClass.Han or ScriptClass.Tangut;

                case >= 0x3220 and <= 0x3229:
                    return script is ScriptClass.Han;

                case >= 0x322A and <= 0x3247:
                    return script is ScriptClass.Han;

                case >= 0x3280 and <= 0x3289:
                    return script is ScriptClass.Han;

                case >= 0x328A and <= 0x32B0:
                    return script is ScriptClass.Han;

                case >= 0x32C0 and <= 0x32CB:
                    return script is ScriptClass.Han;

                case 0x32FF:
                    return script is ScriptClass.Han;

                case >= 0x3358 and <= 0x3370:
                    return script is ScriptClass.Han;

                case >= 0x337B and <= 0x337F:
                    return script is ScriptClass.Han;

                case >= 0x33E0 and <= 0x33FE:
                    return script is ScriptClass.Han;

                case 0xA66F:
                    return script is ScriptClass.Cyrillic or ScriptClass.Glagolitic;

                case >= 0xA700 and <= 0xA707:
                    return script is ScriptClass.Han or ScriptClass.Latin;

                case >= 0xA830 and <= 0xA832:
                    return script is ScriptClass.Devanagari or ScriptClass.Dogra or ScriptClass.Gujarati
                        or ScriptClass.Gurmukhi or ScriptClass.Khojki or ScriptClass.Kannada or ScriptClass.Kaithi
                        or ScriptClass.Mahajani or ScriptClass.Malayalam or ScriptClass.Modi or ScriptClass.Nandinagari
                        or ScriptClass.Sharada or ScriptClass.Khudawadi or ScriptClass.Takri or ScriptClass.Tirhuta
                        or ScriptClass.TuluTigalari;

                case >= 0xA833 and <= 0xA835:
                    return script is ScriptClass.Devanagari or ScriptClass.Dogra or ScriptClass.Gujarati
                        or ScriptClass.Gurmukhi or ScriptClass.Khojki or ScriptClass.Kannada or ScriptClass.Kaithi
                        or ScriptClass.Mahajani or ScriptClass.Modi or ScriptClass.Nandinagari or ScriptClass.Sharada
                        or ScriptClass.Khudawadi or ScriptClass.Takri or ScriptClass.Tirhuta or ScriptClass.TuluTigalari;

                case >= 0xA836 and <= 0xA837:
                    return script is ScriptClass.Devanagari or ScriptClass.Dogra or ScriptClass.Gujarati
                        or ScriptClass.Gurmukhi or ScriptClass.Khojki or ScriptClass.Kaithi or ScriptClass.Mahajani
                        or ScriptClass.Modi or ScriptClass.Khudawadi or ScriptClass.Takri or ScriptClass.Tirhuta;

                case 0xA838:
                    return script is ScriptClass.Devanagari or ScriptClass.Dogra or ScriptClass.Gujarati
                        or ScriptClass.Gurmukhi or ScriptClass.Khojki or ScriptClass.Kaithi or ScriptClass.Mahajani
                        or ScriptClass.Modi or ScriptClass.Sharada or ScriptClass.Khudawadi or ScriptClass.Takri
                        or ScriptClass.Tirhuta;

                case 0xA839:
                    return script is ScriptClass.Devanagari or ScriptClass.Dogra or ScriptClass.Gujarati
                        or ScriptClass.Gurmukhi or ScriptClass.Khojki or ScriptClass.Kaithi or ScriptClass.Mahajani
                        or ScriptClass.Modi or ScriptClass.Khudawadi or ScriptClass.Takri or ScriptClass.Tirhuta;

                case 0xA8F1:
                    return script is ScriptClass.Bengali or ScriptClass.Devanagari or ScriptClass.TuluTigalari;

                case 0xA8F3:
                    return script is ScriptClass.Devanagari or ScriptClass.Tamil;

                case 0xA92E:
                    return script is ScriptClass.KayahLi or ScriptClass.Latin or ScriptClass.Myanmar;

                case 0xA9CF:
                    return script is ScriptClass.Buginese or ScriptClass.Javanese;

                case 0xFD3E:
                    return script is ScriptClass.Arabic or ScriptClass.Nko;

                case 0xFD3F:
                    return script is ScriptClass.Arabic or ScriptClass.Nko;

                case 0xFDF2:
                    return script is ScriptClass.Arabic or ScriptClass.Thaana;

                case 0xFDFD:
                    return script is ScriptClass.Arabic or ScriptClass.Thaana;

                case >= 0xFE45 and <= 0xFE46:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana;

                case 0xFF61:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana or ScriptClass.Yi;

                case 0xFF62:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana or ScriptClass.Yi;

                case 0xFF63:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana or ScriptClass.Yi;

                case >= 0xFF64 and <= 0xFF65:
                    return script is ScriptClass.Bopomofo or ScriptClass.Hangul or ScriptClass.Han
                        or ScriptClass.Hiragana or ScriptClass.Katakana or ScriptClass.Yi;

                case 0xFF70:
                    return script is ScriptClass.Hiragana or ScriptClass.Katakana;

                case >= 0xFF9E and <= 0xFF9F:
                    return script is ScriptClass.Hiragana or ScriptClass.Katakana;

                case >= 0x10100 and <= 0x10101:
                    return script is ScriptClass.CyproMinoan or ScriptClass.Cypriot or ScriptClass.LinearB;

                case 0x10102:
                    return script is ScriptClass.Cypriot or ScriptClass.LinearB;

                case >= 0x10107 and <= 0x10133:
                    return script is ScriptClass.Cypriot or ScriptClass.LinearA or ScriptClass.LinearB;

                case >= 0x10137 and <= 0x1013F:
                    return script is ScriptClass.Cypriot or ScriptClass.LinearB;

                case 0x102E0:
                    return script is ScriptClass.Arabic or ScriptClass.Coptic;

                case >= 0x102E1 and <= 0x102FB:
                    return script is ScriptClass.Arabic or ScriptClass.Coptic;

                case 0x10AF2:
                    return script is ScriptClass.Manichaean or ScriptClass.OldUyghur;

                case 0x11301:
                    return script is ScriptClass.Grantha or ScriptClass.Tamil;

                case 0x11303:
                    return script is ScriptClass.Grantha or ScriptClass.Tamil;

                case >= 0x1133B and <= 0x1133C:
                    return script is ScriptClass.Grantha or ScriptClass.Tamil;

                case >= 0x11FD0 and <= 0x11FD1:
                    return script is ScriptClass.Grantha or ScriptClass.Tamil;

                case 0x11FD3:
                    return script is ScriptClass.Grantha or ScriptClass.Tamil;

                case >= 0x1BCA0 and <= 0x1BCA3:
                    return script is ScriptClass.Duployan;

                case >= 0x1D360 and <= 0x1D371:
                    return script is ScriptClass.Han;

                case >= 0x1F250 and <= 0x1F251:
                    return script is ScriptClass.Han;

                default:
                    return false;
            }
        }
    }
}
